prod:
  image: vizzuality/gfw-forma-alerts-api:2.0.0${STAGING}
  ports:
    - "3600"
  env_file:
    - prod.env
  command: start
  dns: ${DNS_SERVER}
  log_driver: "gelf"
  restart: always
  log_opt:
    syslog-address: ${SYSLOG_ADDRESS}
    tag: gfw-forma${STAGING}
